[tool.poetry]
name = "mirror-heat-flux"
package-mode = false
version = "0.1.0"
description = "Project for estimating mirror heat flux"
authors = ["Henry Wietfeldt <henrycw@psfc.mit.edu>"]

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.0.0"
matplotlib = "^3.10.7"
scipy = "^1.16.2"
